name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: cd doc && make
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: index.html
        path: _build/html/*
